//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOA.WCF.Web.UnitTestProject.MyWebWCF {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MyWebWCF.IMyWCF")]
    public interface IMyWCF {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyWCF/DoWork", ReplyAction="http://tempuri.org/IMyWCF/DoWorkResponse")]
        SOA.WCF.Web.UnitTestProject.MyWebWCF.DoWorkResponse DoWork(SOA.WCF.Web.UnitTestProject.MyWebWCF.DoWorkRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyWCF/DoWork", ReplyAction="http://tempuri.org/IMyWCF/DoWorkResponse")]
        System.Threading.Tasks.Task<SOA.WCF.Web.UnitTestProject.MyWebWCF.DoWorkResponse> DoWorkAsync(SOA.WCF.Web.UnitTestProject.MyWebWCF.DoWorkRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyWCF/GetUserName", ReplyAction="http://tempuri.org/IMyWCF/GetUserNameResponse")]
        SOA.WCF.Web.UnitTestProject.MyWebWCF.GetUserNameResponse GetUserName(SOA.WCF.Web.UnitTestProject.MyWebWCF.GetUserNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyWCF/GetUserName", ReplyAction="http://tempuri.org/IMyWCF/GetUserNameResponse")]
        System.Threading.Tasks.Task<SOA.WCF.Web.UnitTestProject.MyWebWCF.GetUserNameResponse> GetUserNameAsync(SOA.WCF.Web.UnitTestProject.MyWebWCF.GetUserNameRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DoWork", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DoWorkRequest {
        
        public DoWorkRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DoWorkResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DoWorkResponse {
        
        public DoWorkResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetUserName", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetUserNameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string name;
        
        public GetUserNameRequest() {
        }
        
        public GetUserNameRequest(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetUserNameResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetUserNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string GetUserNameResult;
        
        public GetUserNameResponse() {
        }
        
        public GetUserNameResponse(string GetUserNameResult) {
            this.GetUserNameResult = GetUserNameResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMyWCFChannel : SOA.WCF.Web.UnitTestProject.MyWebWCF.IMyWCF, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MyWCFClient : System.ServiceModel.ClientBase<SOA.WCF.Web.UnitTestProject.MyWebWCF.IMyWCF>, SOA.WCF.Web.UnitTestProject.MyWebWCF.IMyWCF {
        
        public MyWCFClient() {
        }
        
        public MyWCFClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MyWCFClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyWCFClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyWCFClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SOA.WCF.Web.UnitTestProject.MyWebWCF.DoWorkResponse DoWork(SOA.WCF.Web.UnitTestProject.MyWebWCF.DoWorkRequest request) {
            return base.Channel.DoWork(request);
        }
        
        public System.Threading.Tasks.Task<SOA.WCF.Web.UnitTestProject.MyWebWCF.DoWorkResponse> DoWorkAsync(SOA.WCF.Web.UnitTestProject.MyWebWCF.DoWorkRequest request) {
            return base.Channel.DoWorkAsync(request);
        }
        
        public SOA.WCF.Web.UnitTestProject.MyWebWCF.GetUserNameResponse GetUserName(SOA.WCF.Web.UnitTestProject.MyWebWCF.GetUserNameRequest request) {
            return base.Channel.GetUserName(request);
        }
        
        public System.Threading.Tasks.Task<SOA.WCF.Web.UnitTestProject.MyWebWCF.GetUserNameResponse> GetUserNameAsync(SOA.WCF.Web.UnitTestProject.MyWebWCF.GetUserNameRequest request) {
            return base.Channel.GetUserNameAsync(request);
        }
    }
}
